var possiblewins = [
    ["um", "dois", "tres"],
    ["um", "tres", "dois"],
    ["dois", "um", "tres"],
    ["dois", "tres", "um"],
    ["tres", "dois", "um"],
    ["tres", "um", "dois"],

    ["um", "quatro", "sete"],
    ["um", "sete", "quatro"],
    ["sete", "quatro", "um"],
    ["sete", "um", "quatro"],
    ["quatro", "sete", "um"],
    ["quatro", "um", "sete"],

    ["um", "cinco", "nove"],
    ["um", "nove", "cinco"],
    ["cinco", "um", "nove"],
    ["cinco", "nove", "um"],
    ["nove", "cinco", "um"],
    ["nove", "um", "cinco"],

    ["nove", "cinco", "um"],
    ["nove", "um", "cinco"],
    ["cinco", "nove", "um"],
    ["cinco", "um", "nove"],
    ["nove", "cinco", "um"],
    ["nove", "um", "cinco"],

    ["dois", "cinco", "oito"],
    ["dois", "oito", "cinco"],
    ["cinco", "dois", "oito"],
    ["cinco", "oito", "dois"],
    ["oito", "cinco", "dois"],
    ["oito", "dois", "cinco"],
    
    ["quatro", "cinco", "seis"],
    ["quatro", "seis", "cinco"],
    ["seis", "cinco", "quatro"],
    ["seis", "quatro", "cinco"],
    ["cinco", "quatro", "seis"],
    ["cinco", "seis", "quatro"],

    ["sete", "oito", "nove"],
    ["sete", "nove", "oito"],
    ["nove", "sete", "oito"],
    ["nove", "oito", "sete"],
    ["oito", "nove", "sete"],
    ["oito", "sete", "nove"],

    ["sete", "cinco", "tres"],
    ["sete", "tres", "cinco"],
    ["tres", "sete", "cinco"],
    ["tres", "cinco", "sete"],
    ["cinco", "tres", "sete"],
    ["cinco", "sete", "tres"],

    ["tres", "seis", "nove"],
    ["tres", "nove", "seis"],
    ["seis", "tres", "nove"],
    ["seis", "nove", "tres"],
    ["nove", "seis", "tres"],
    ["nove", "tres", "seis"],
]

// export { possiblewins }